/**
 * Transcription Service
 *
 * Handles audio transcription. Currently uses a stub implementation
 * that simulates Whisper-like behavior. Can be replaced with real
 * Whisper API, server-side transcription, or other services later.
 */

/**
 * Stub transcription function.
 * In production, this would call a real transcription service
 * (e.g., Whisper API, server endpoint, etc.).
 *
 * For now, returns a plausible transcript based on the title
 * and a short placeholder to simulate real behavior.
 */
export async function transcribeAudio(
  fileUri: string,
  title: string,
  theme: string,
): Promise<string> {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 500));

  // Stub response: generate a plausible transcript
  // In a real implementation, this would call a transcription API
  const themeContext: Record<string, string> = {
    childhood: 'When I was young, ',
    recipes: 'To make this dish, ',
    love: 'I remember when we first met, ',
    work: 'During my career, ',
    advice: 'What I learned is that ',
    faith: 'My faith has always been important because ',
  };

  const prefix = themeContext[theme] || 'I remember ';
  const transcript = `${prefix}${title}. This is a placeholder transcript that would be generated by a real transcription service. The audio file at ${fileUri} would be processed to extract the actual spoken content.`;

  return transcript;
}

/**
 * Check if transcription is available for a memory.
 * Used to determine whether to show transcript in UI.
 */
export function hasTranscript(transcript: string | null | undefined): boolean {
  return !!transcript && transcript.trim().length > 0;
}
